### PR TITLE
Raise Impersonated event

### PR DESCRIPTION
**Pull request by imorland**
- Raise an event when a user is impersonated

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Could it make sense to instead dispatch an `Impersonated` event from this extension, and have the Moderator Notes extension react to that event ? I feel like this would make for a cleaner API.

**Comment by imorland** [comment]
Yes! I'm already doing just that :)

**Review by clarkwinkelmann — APPROVED** [review]
I have not tested locally, but it's looking good.

Personally I wouldn't document the `Impersonated` constructor seeing it's not providing any additional information to what type-hinting already does.

**Comment by imorland** [comment]
Cool, thank you

**Pull request merged**
